apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/paldab/argo-apps.git
        revision: HEAD
        files:
          - path: argo-applications/*
  template:
    metadata:
      name: '{{.path.basename}}' 
    spec:
      project: default
      source:
        repoURL: https://github.com/paldab/argo-apps.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
          - pruneLast=true
          - CreateNamespace=true
