apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gospel-clip-generator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paldab/argo-apps.git
    chart: gospel-clip-generator
    targetRevision: 0.1.0
    path: gospel-clip-generator
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gospel
  syncPolicy:
    syncOptions:
      - pruneLast=true
